'use client'
import Head from 'next/head'
import styles from './index.module.css'
import { getNfeStatusServico } from '~/dfe-comunica-sefaz/comunicaSefaz'
import { ModeloDocumento, TipoAmbiente } from '~/dfe-comunica-sefaz/types/nfe/tipos'
import { UfEmi } from '~/dfe-comunica-sefaz/types/uf'

export default function Home() {
  const carregaXml = async () => {
    console.log('carregaXML')
    const result = await getNfeStatusServico(UfEmi.RS, ModeloDocumento.NFe, TipoAmbiente.Producao1)
    console.log(result)
  }

  return (
    <>
      <Head>
        <title>Comunica sefaz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Communica <span className={styles.pinkSpan}>Sefaz</span> Teste
          </h1>
          <div className={styles.cardRow}>
            <button type="button" onClick={() => void carregaXml()} className={styles.card}>
              <h3 className={styles.cardTitle}>consultaStatus</h3>
            </button>
          </div>
        </div>
      </main>
    </>
  )
}
